### ISSUE TITLE
Transaction log files got corrupted

### ISSUE THREAD

**Issue by Maddy-2999** [javaee/glassfish#21781]
Hi Team,

We are using Glassfish 3.1.2.2 version.
Recently, we found an issue related to transaction log files in (domains/domain1/logs/server/tx) path while performing some usecase. And when we clear the logs and perform the usecase, we don't see any issue. While we are not sure why the transaction logs could have been corrupted in the first place, could you please help with the same?
As in in what major scenarios would the transaction logs get corrupted?

**Comment by yaminikb** [comment]
Well, its hard to make a list of scenarios, its like any file corruption. Transaction log corruptions are rare. Some cases that I can think of are
-unexpected or unclean shutdown
-server crash
-I/O error
-NFS issues if transaction logs are on shared location
One option is to back up logs periodically (GlassFish has a collect-log-files command as well) so that they can be restored in case of problems. In the absence of backups, clearing or removing the transaction logs is the most common solution for getting over problems due to corruption.

**Comment by Maddy-2999** [comment]
Oh. Thanks !! 👍
